#!/bin/sh

set -e
cd "$(dirname "$0")/.."

echo "==> Installing dependencies..."

if [ "$(uname -s)" = "Darwin" ]; then
  echo "==> Installing Homebrew dependencies..."
  brew update
  brew tap caskroom/cask
  brew install brew-cask
  brew cask install java
  brew install sbt
  brew install node
  echo "==> Installed Homebrew dependencies."
fi

echo "==> Installed dependencies."
