#!/bin/sh

set -e
cd "$(dirname "$0")/.."

echo "===> Starting CI tests..." 

startdate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
echo "==> Tests started at $startdate..."

script/test

# deploy to test machine and run acceptance tests

echo "===> CI tests finished." 
