#!/bin/sh

set -e
cd "$(dirname "$0")/.."

echo "===> Starting the Application..."

script/update
script/prebuild


root=$(pwd)
cd ${root}/ui
gulp &
cd ${root}/api
sbt run

echo "===> Application is running."
